apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${moduleName}
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: ${moduleName}
  project: default
  sources:
    - repoURL: '${codeRepoSSHUrl}'
      targetRevision: 'main'
      ref: codeRepo
    - repoURL: "https://github.com/entigolabs/entigo-infralib-release.git"
      targetRevision: '${moduleVersion}'
      path: "modules/k8s/${moduleSource}"
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - 'values.yaml'
          - '$codeRepo/${valuesFilePath}'
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[].failurePolicy
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.service.name
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions:
    - .spec.conversion.webhook.clientConfig.service.name
