source: https://github.com/entigolabs/entigo-infralib-release
base_config:
  profile: biz
steps:
  - name: infrastructure
    workspace: test
    modules:
      - name: dns
        inputs:
          vpc_prefix: "ep-network-vpc"
          parent_zone_id: "Z07983041XRLSLZUTHHDY"
      - name: argocd
        inputs:
          hostname: "argocd.runner-main-biz-int.infralib.entigo.io"
  - name: applications
    workspace: test
    modules:
      - name: istio-istiod
        inputs:
          domain: "*.ep-test.infralib.entigo.io"
          altdomain:
            - "*.something.ep-test.infralib.entigo.io"