source: https://github.com/entigolabs/entigo-infralib-release
base_config:
  profile: biz
steps:
  - name: infrastructure
    workspace: test
    provider:
      aws:
        ignore_tags:
          key_prefixes:
          - ignorebeginningoftag
          keys:
          - ignoretag
        default_tags:
          tags:
            hat-migrated: hat-x
      kubernetes:
        ignore_annotations:
        - ignoreannotation
        ignore_labels:
        -  ignorelabel
    modules:
      - name: dns
        inputs:
          vpc_prefix: "ep-network-vpc"
          parent_zone_id: "Z07983041XRLSLZUTHHDY"
      - name: eks
        inputs:
          eks_cluster_public: true
  - name: helm
    workspace: test
    modules:
      - name: argocd
        inputs:
          hostname: "argocd.ep-infrastructure-dns-test.infralib.entigo.io"
          ingress_group_name: "external"
          ingress_scheme: "internet-facing"
  - name: mycustomtf
    type: terraform-custom
    workspace: test
    vpc_prefix: network-vpc
    approve: never
  - name: applications
    workspace: test
    modules:
      - name: istio-gateway
        inputs:
          domain: "*.ep-infrastructure-dns-test.infralib.entigo.io"

