// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ApplyStatus.
const (
	ApplyStatusFailure  ApplyStatus = "failure"
	ApplyStatusSkipped  ApplyStatus = "skipped"
	ApplyStatusStarting ApplyStatus = "starting"
	ApplyStatusSuccess  ApplyStatus = "success"
)

// Valid indicates whether the value is a known member of the ApplyStatus enum.
func (e ApplyStatus) Valid() bool {
	switch e {
	case ApplyStatusFailure:
		return true
	case ApplyStatusSkipped:
		return true
	case ApplyStatusStarting:
		return true
	case ApplyStatusSuccess:
		return true
	default:
		return false
	}
}

// Defines values for ApprovalNotificationKind.
const (
	Approval ApprovalNotificationKind = "approval"
)

// Valid indicates whether the value is a known member of the ApprovalNotificationKind enum.
func (e ApprovalNotificationKind) Valid() bool {
	switch e {
	case Approval:
		return true
	default:
		return false
	}
}

// Defines values for CampaignNotificationKind.
const (
	Campaign CampaignNotificationKind = "campaign"
)

// Valid indicates whether the value is a known member of the CampaignNotificationKind enum.
func (e CampaignNotificationKind) Valid() bool {
	switch e {
	case Campaign:
		return true
	default:
		return false
	}
}

// Defines values for CampaignStatus.
const (
	CampaignStatusFailure    CampaignStatus = "failure"
	CampaignStatusStarted    CampaignStatus = "started"
	CampaignStatusSuccess    CampaignStatus = "success"
	CampaignStatusTerminated CampaignStatus = "terminated"
)

// Valid indicates whether the value is a known member of the CampaignStatus enum.
func (e CampaignStatus) Valid() bool {
	switch e {
	case CampaignStatusFailure:
		return true
	case CampaignStatusStarted:
		return true
	case CampaignStatusSuccess:
		return true
	case CampaignStatusTerminated:
		return true
	default:
		return false
	}
}

// Defines values for Command.
const (
	Run    Command = "run"
	Update Command = "update"
)

// Valid indicates whether the value is a known member of the Command enum.
func (e Command) Valid() bool {
	switch e {
	case Run:
		return true
	case Update:
		return true
	default:
		return false
	}
}

// Defines values for ManualApprovalNotificationKind.
const (
	ManualApproval ManualApprovalNotificationKind = "manual_approval"
)

// Valid indicates whether the value is a known member of the ManualApprovalNotificationKind enum.
func (e ManualApprovalNotificationKind) Valid() bool {
	switch e {
	case ManualApproval:
		return true
	default:
		return false
	}
}

// Defines values for ModulesNotificationKind.
const (
	Modules ModulesNotificationKind = "modules"
)

// Valid indicates whether the value is a known member of the ModulesNotificationKind enum.
func (e ModulesNotificationKind) Valid() bool {
	switch e {
	case Modules:
		return true
	default:
		return false
	}
}

// Defines values for PipelineStateNotificationKind.
const (
	PipelineState PipelineStateNotificationKind = "pipeline_state"
)

// Valid indicates whether the value is a known member of the PipelineStateNotificationKind enum.
func (e PipelineStateNotificationKind) Valid() bool {
	switch e {
	case PipelineState:
		return true
	default:
		return false
	}
}

// Defines values for ProviderType.
const (
	AWS    ProviderType = "AWS"
	GCLOUD ProviderType = "GCLOUD"
)

// Valid indicates whether the value is a known member of the ProviderType enum.
func (e ProviderType) Valid() bool {
	switch e {
	case AWS:
		return true
	case GCLOUD:
		return true
	default:
		return false
	}
}

// Defines values for ScheduleNotificationAction.
const (
	Added    ScheduleNotificationAction = "added"
	Modified ScheduleNotificationAction = "modified"
	Removed  ScheduleNotificationAction = "removed"
)

// Valid indicates whether the value is a known member of the ScheduleNotificationAction enum.
func (e ScheduleNotificationAction) Valid() bool {
	switch e {
	case Added:
		return true
	case Modified:
		return true
	case Removed:
		return true
	default:
		return false
	}
}

// Defines values for ScheduleNotificationKind.
const (
	Schedule ScheduleNotificationKind = "schedule"
)

// Valid indicates whether the value is a known member of the ScheduleNotificationKind enum.
func (e ScheduleNotificationKind) Valid() bool {
	switch e {
	case Schedule:
		return true
	default:
		return false
	}
}

// Defines values for SourcesNotificationKind.
const (
	Sources SourcesNotificationKind = "sources"
)

// Valid indicates whether the value is a known member of the SourcesNotificationKind enum.
func (e SourcesNotificationKind) Valid() bool {
	switch e {
	case Sources:
		return true
	default:
		return false
	}
}

// Defines values for StepEntityType.
const (
	ArgocdApps StepEntityType = "argocd-apps"
	Terraform  StepEntityType = "terraform"
)

// Valid indicates whether the value is a known member of the StepEntityType enum.
func (e StepEntityType) Valid() bool {
	switch e {
	case ArgocdApps:
		return true
	case Terraform:
		return true
	default:
		return false
	}
}

// Defines values for StepStateNotificationKind.
const (
	StepState StepStateNotificationKind = "step_state"
)

// Valid indicates whether the value is a known member of the StepStateNotificationKind enum.
func (e StepStateNotificationKind) Valid() bool {
	switch e {
	case StepState:
		return true
	default:
		return false
	}
}

// ApplyStatus defines model for ApplyStatus.
type ApplyStatus string

// ApprovalNotification defines model for ApprovalNotification.
type ApprovalNotification struct {
	ApprovedBy *string `json:"approvedBy,omitempty"`

	// Context Optional context label configured on the notifier
	Context *string                  `json:"context,omitempty"`
	Kind    ApprovalNotificationKind `json:"kind"`
	Name    string                   `json:"name"`

	// NotificationId Unique identifier for the notification
	NotificationId openapi_types.UUID `json:"notificationId"`
	PipelineIndex  int                `json:"pipelineIndex"`
	Step           string             `json:"step"`
	Timestamp      time.Time          `json:"timestamp"`
}

// ApprovalNotificationKind defines model for ApprovalNotification.Kind.
type ApprovalNotificationKind string

// CampaignNotification defines model for CampaignNotification.
type CampaignNotification struct {
	Command Command `json:"command"`

	// Context Optional context label configured on the notifier
	Context *string                  `json:"context,omitempty"`
	Error   *string                  `json:"error,omitempty"`
	Id      string                   `json:"id"`
	Kind    CampaignNotificationKind `json:"kind"`

	// NotificationId Unique identifier for the notification
	NotificationId openapi_types.UUID `json:"notificationId"`
	Provider       ProviderType       `json:"provider"`
	Region         string             `json:"region"`
	Status         CampaignStatus     `json:"status"`
	Timestamp      time.Time          `json:"timestamp"`
}

// CampaignNotificationKind defines model for CampaignNotification.Kind.
type CampaignNotificationKind string

// CampaignStatus defines model for CampaignStatus.
type CampaignStatus string

// Command defines model for Command.
type Command string

// ManualApprovalNotification defines model for ManualApprovalNotification.
type ManualApprovalNotification struct {
	// Context Optional context label configured on the notifier
	Context *string                        `json:"context,omitempty"`
	Kind    ManualApprovalNotificationKind `json:"kind"`
	Link    *string                        `json:"link,omitempty"`
	Name    string                         `json:"name"`

	// NotificationId Unique identifier for the notification
	NotificationId openapi_types.UUID `json:"notificationId"`
	PipelineIndex  int                `json:"pipelineIndex"`
	Plan           PlanEntity         `json:"plan"`
	Step           string             `json:"step"`
	Timestamp      time.Time          `json:"timestamp"`
}

// ManualApprovalNotificationKind defines model for ManualApprovalNotification.Kind.
type ManualApprovalNotificationKind string

// ModuleEntity defines model for ModuleEntity.
type ModuleEntity struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

// ModulesNotification defines model for ModulesNotification.
type ModulesNotification struct {
	Command Command `json:"command"`

	// Context Optional context label configured on the notifier
	Context *string                 `json:"context,omitempty"`
	Id      string                  `json:"id"`
	Kind    ModulesNotificationKind `json:"kind"`

	// NotificationId Unique identifier for the notification
	NotificationId openapi_types.UUID `json:"notificationId"`
	Provider       ProviderType       `json:"provider"`
	Region         string             `json:"region"`
	Steps          []StepEntity       `json:"steps"`
	Timestamp      time.Time          `json:"timestamp"`
	UpdateSchedule *string            `json:"updateSchedule,omitempty"`
}

// ModulesNotificationKind defines model for ModulesNotification.Kind.
type ModulesNotificationKind string

// Notification defines model for Notification.
type Notification struct {
	union json.RawMessage
}

// NotificationBase defines model for NotificationBase.
type NotificationBase struct {
	// Context Optional context label configured on the notifier
	Context *string `json:"context,omitempty"`

	// Kind Discriminator for the notification variant
	Kind string `json:"kind"`

	// NotificationId Unique identifier for the notification
	NotificationId openapi_types.UUID `json:"notificationId"`
	Timestamp      time.Time          `json:"timestamp"`
}

// PipelineStateNotification defines model for PipelineStateNotification.
type PipelineStateNotification struct {
	// Context Optional context label configured on the notifier
	Context *string                       `json:"context,omitempty"`
	Error   *string                       `json:"error,omitempty"`
	Kind    PipelineStateNotificationKind `json:"kind"`

	// NotificationId Unique identifier for the notification
	NotificationId openapi_types.UUID `json:"notificationId"`
	PipelineIndex  int                `json:"pipelineIndex"`
	Status         ApplyStatus        `json:"status"`
	Timestamp      time.Time          `json:"timestamp"`
	Versions       []PipelineVersion  `json:"versions"`
}

// PipelineStateNotificationKind defines model for PipelineStateNotification.Kind.
type PipelineStateNotificationKind string

// PipelineVersion defines model for PipelineVersion.
type PipelineVersion struct {
	ForcedVersion *string `json:"forcedVersion,omitempty"`
	Url           string  `json:"url"`
	Version       *string `json:"version,omitempty"`
}

// PlanEntity defines model for PlanEntity.
type PlanEntity struct {
	Added     int `json:"added"`
	Changed   int `json:"changed"`
	Destroyed int `json:"destroyed"`
	Imported  int `json:"imported"`
}

// ProviderType defines model for ProviderType.
type ProviderType string

// ScheduleNotification defines model for ScheduleNotification.
type ScheduleNotification struct {
	Action  ScheduleNotificationAction `json:"action,omitempty"`
	Command Command                    `json:"command"`

	// Context Optional context label configured on the notifier
	Context *string                  `json:"context,omitempty"`
	Kind    ScheduleNotificationKind `json:"kind"`

	// NotificationId Unique identifier for the notification
	NotificationId openapi_types.UUID `json:"notificationId"`

	// Schedule Cron expression for the campaign schedule
	Schedule  *string   `json:"schedule,omitempty"`
	Timestamp time.Time `json:"timestamp"`
}

// ScheduleNotificationAction defines model for ScheduleNotification.Action.
type ScheduleNotificationAction string

// ScheduleNotificationKind defines model for ScheduleNotification.Kind.
type ScheduleNotificationKind string

// SourceEntity defines model for SourceEntity.
type SourceEntity struct {
	ForcedVersion *string   `json:"forcedVersion,omitempty"`
	Modules       *[]string `json:"modules,omitempty"`
	Releases      *[]string `json:"releases,omitempty"`
	Url           string    `json:"url"`
	Version       *string   `json:"version,omitempty"`
}

// SourcesNotification defines model for SourcesNotification.
type SourcesNotification struct {
	// Context Optional context label configured on the notifier
	Context *string                 `json:"context,omitempty"`
	Kind    SourcesNotificationKind `json:"kind"`

	// NotificationId Unique identifier for the notification
	NotificationId openapi_types.UUID `json:"notificationId"`
	Sources        []SourceEntity     `json:"sources"`
	Timestamp      time.Time          `json:"timestamp"`
}

// SourcesNotificationKind defines model for SourcesNotification.Kind.
type SourcesNotificationKind string

// StepEntity defines model for StepEntity.
type StepEntity struct {
	Modules []ModuleEntity `json:"modules"`
	Name    string         `json:"name"`
	Type    StepEntityType `json:"type"`
}

// StepEntityType defines model for StepEntity.Type.
type StepEntityType string

// StepModuleStatus defines model for StepModuleStatus.
type StepModuleStatus struct {
	AppliedVersion *string            `json:"applied_version,omitempty"`
	Metadata       *map[string]string `json:"metadata,omitempty"`
	Name           string             `json:"name"`
	Version        string             `json:"version"`
}

// StepStateNotification defines model for StepStateNotification.
type StepStateNotification struct {
	AppliedAt *time.Time `json:"applied_at,omitempty"`

	// Context Optional context label configured on the notifier
	Context *string                   `json:"context,omitempty"`
	Error   *string                   `json:"error,omitempty"`
	Kind    StepStateNotificationKind `json:"kind"`
	Modules []StepModuleStatus        `json:"modules"`

	// NotificationId Unique identifier for the notification
	NotificationId openapi_types.UUID `json:"notificationId"`
	PipelineIndex  int                `json:"pipelineIndex"`
	Status         ApplyStatus        `json:"status"`
	Step           string             `json:"step"`
	Timestamp      time.Time          `json:"timestamp"`
}

// StepStateNotificationKind defines model for StepStateNotification.Kind.
type StepStateNotificationKind string

// CampaignId defines model for campaignId.
type CampaignId = openapi_types.UUID

// PostNotificationJSONRequestBody defines body for PostNotification for application/json ContentType.
type PostNotificationJSONRequestBody = Notification

// AsCampaignNotification returns the union data inside the Notification as a CampaignNotification
func (t Notification) AsCampaignNotification() (CampaignNotification, error) {
	var body CampaignNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromCampaignNotification overwrites any union data inside the Notification as the provided CampaignNotification
func (t *Notification) FromCampaignNotification(v CampaignNotification) error {
	v.Kind = "campaign"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeCampaignNotification performs a merge with any union data inside the Notification, using the provided CampaignNotification
func (t *Notification) MergeCampaignNotification(v CampaignNotification) error {
	v.Kind = "campaign"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsScheduleNotification returns the union data inside the Notification as a ScheduleNotification
func (t Notification) AsScheduleNotification() (ScheduleNotification, error) {
	var body ScheduleNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromScheduleNotification overwrites any union data inside the Notification as the provided ScheduleNotification
func (t *Notification) FromScheduleNotification(v ScheduleNotification) error {
	v.Kind = "schedule"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeScheduleNotification performs a merge with any union data inside the Notification, using the provided ScheduleNotification
func (t *Notification) MergeScheduleNotification(v ScheduleNotification) error {
	v.Kind = "schedule"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsApprovalNotification returns the union data inside the Notification as a ApprovalNotification
func (t Notification) AsApprovalNotification() (ApprovalNotification, error) {
	var body ApprovalNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromApprovalNotification overwrites any union data inside the Notification as the provided ApprovalNotification
func (t *Notification) FromApprovalNotification(v ApprovalNotification) error {
	v.Kind = "approval"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeApprovalNotification performs a merge with any union data inside the Notification, using the provided ApprovalNotification
func (t *Notification) MergeApprovalNotification(v ApprovalNotification) error {
	v.Kind = "approval"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsManualApprovalNotification returns the union data inside the Notification as a ManualApprovalNotification
func (t Notification) AsManualApprovalNotification() (ManualApprovalNotification, error) {
	var body ManualApprovalNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromManualApprovalNotification overwrites any union data inside the Notification as the provided ManualApprovalNotification
func (t *Notification) FromManualApprovalNotification(v ManualApprovalNotification) error {
	v.Kind = "manual_approval"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeManualApprovalNotification performs a merge with any union data inside the Notification, using the provided ManualApprovalNotification
func (t *Notification) MergeManualApprovalNotification(v ManualApprovalNotification) error {
	v.Kind = "manual_approval"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStepStateNotification returns the union data inside the Notification as a StepStateNotification
func (t Notification) AsStepStateNotification() (StepStateNotification, error) {
	var body StepStateNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStepStateNotification overwrites any union data inside the Notification as the provided StepStateNotification
func (t *Notification) FromStepStateNotification(v StepStateNotification) error {
	v.Kind = "step_state"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStepStateNotification performs a merge with any union data inside the Notification, using the provided StepStateNotification
func (t *Notification) MergeStepStateNotification(v StepStateNotification) error {
	v.Kind = "step_state"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPipelineStateNotification returns the union data inside the Notification as a PipelineStateNotification
func (t Notification) AsPipelineStateNotification() (PipelineStateNotification, error) {
	var body PipelineStateNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPipelineStateNotification overwrites any union data inside the Notification as the provided PipelineStateNotification
func (t *Notification) FromPipelineStateNotification(v PipelineStateNotification) error {
	v.Kind = "pipeline_state"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePipelineStateNotification performs a merge with any union data inside the Notification, using the provided PipelineStateNotification
func (t *Notification) MergePipelineStateNotification(v PipelineStateNotification) error {
	v.Kind = "pipeline_state"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsModulesNotification returns the union data inside the Notification as a ModulesNotification
func (t Notification) AsModulesNotification() (ModulesNotification, error) {
	var body ModulesNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromModulesNotification overwrites any union data inside the Notification as the provided ModulesNotification
func (t *Notification) FromModulesNotification(v ModulesNotification) error {
	v.Kind = "modules"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeModulesNotification performs a merge with any union data inside the Notification, using the provided ModulesNotification
func (t *Notification) MergeModulesNotification(v ModulesNotification) error {
	v.Kind = "modules"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSourcesNotification returns the union data inside the Notification as a SourcesNotification
func (t Notification) AsSourcesNotification() (SourcesNotification, error) {
	var body SourcesNotification
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSourcesNotification overwrites any union data inside the Notification as the provided SourcesNotification
func (t *Notification) FromSourcesNotification(v SourcesNotification) error {
	v.Kind = "sources"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSourcesNotification performs a merge with any union data inside the Notification, using the provided SourcesNotification
func (t *Notification) MergeSourcesNotification(v SourcesNotification) error {
	v.Kind = "sources"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Notification) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"kind"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Notification) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "approval":
		return t.AsApprovalNotification()
	case "campaign":
		return t.AsCampaignNotification()
	case "manual_approval":
		return t.AsManualApprovalNotification()
	case "modules":
		return t.AsModulesNotification()
	case "pipeline_state":
		return t.AsPipelineStateNotification()
	case "schedule":
		return t.AsScheduleNotification()
	case "sources":
		return t.AsSourcesNotification()
	case "step_state":
		return t.AsStepStateNotification()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Notification) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Notification) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostNotificationWithBody request with any body
	PostNotificationWithBody(ctx context.Context, campaignId CampaignId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostNotification(ctx context.Context, campaignId CampaignId, body PostNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostNotificationWithBody(ctx context.Context, campaignId CampaignId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostNotificationRequestWithBody(c.Server, campaignId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostNotification(ctx context.Context, campaignId CampaignId, body PostNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostNotificationRequest(c.Server, campaignId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostNotificationRequest calls the generic PostNotification builder with application/json body
func NewPostNotificationRequest(server string, campaignId CampaignId, body PostNotificationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostNotificationRequestWithBody(server, campaignId, "application/json", bodyReader)
}

// NewPostNotificationRequestWithBody generates requests for PostNotification with any type of body
func NewPostNotificationRequestWithBody(server string, campaignId CampaignId, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "campaignId", campaignId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/campaigns/%s/notifications", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostNotificationWithBodyWithResponse request with any body
	PostNotificationWithBodyWithResponse(ctx context.Context, campaignId CampaignId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostNotificationResponse, error)

	PostNotificationWithResponse(ctx context.Context, campaignId CampaignId, body PostNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostNotificationResponse, error)
}

type PostNotificationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostNotificationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostNotificationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r PostNotificationResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// PostNotificationWithBodyWithResponse request with arbitrary body returning *PostNotificationResponse
func (c *ClientWithResponses) PostNotificationWithBodyWithResponse(ctx context.Context, campaignId CampaignId, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostNotificationResponse, error) {
	rsp, err := c.PostNotificationWithBody(ctx, campaignId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostNotificationResponse(rsp)
}

func (c *ClientWithResponses) PostNotificationWithResponse(ctx context.Context, campaignId CampaignId, body PostNotificationJSONRequestBody, reqEditors ...RequestEditorFn) (*PostNotificationResponse, error) {
	rsp, err := c.PostNotification(ctx, campaignId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostNotificationResponse(rsp)
}

// ParsePostNotificationResponse parses an HTTP response from a PostNotificationWithResponse call
func ParsePostNotificationResponse(rsp *http.Response) (*PostNotificationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostNotificationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}
