apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: '{{moduleName}}'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: '{{moduleName}}'
  project: default
  sources:
    - repoURL: '{{moduleSourceURL}}'
      targetRevision: '{{moduleVersion}}'
      path: "modules/k8s/{{moduleSource}}"
      helm:
        ignoreMissingValueFiles: true
        valueFiles:
          - 'values.yaml'
          - 'values-{{cloudProvider}}.yaml'
        values: |
          {{moduleValues}}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
      - Retry=true
    retry:
      limit: 6
      backoff:
        duration: 15s
