apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: entigo-infralib
description: Deployment pipeline for entigo-infralib
serialPipeline:
  stages:
    - targetId: plan-cloudrun-job
      profiles: [plan]
    - targetId: apply-cloudrun-job
      profiles: [apply]