apiVersion: run.googleapis.com/v1
kind: Job
metadata:
  name: entigo-infralib-apply
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/network-interfaces: |
          [
            {
              "network": "runner-main-biz",
              "subnetwork": "runner-main-biz"
            }
          ]
    spec:
      template:
        spec:
          containers:
            - image: docker.io/entigolabs/entigo-infralib-base:latest
              name: terraform
              env:
                - name: PROJECT_NAME
                  value: ep-net-dev
                - name: CODEBUILD_SRC_DIR
                  value: /bucket
                - name: GOOGLE_REGION
                  value: europe-north1
                - name: GOOGLE_PROJECT
                  value: entigo-infralib
                - name: COMMAND
                  value: apply
                - name: TF_VAR_prefix
                  value: ep-net
              volumeMounts:
                - name: bucket
                  mountPath: /bucket
                - name: project
                  mountPath: /project
          volumes:
            - name: bucket
              csi:
                driver: gcsfuse.run.googleapis.com
                volumeAttributes:
                  bucketName: entigo-infralib-entigo-infralib
            - name: project
              emptyDir:
                sizeLimit: 1Gi
          timeoutSeconds: "86400"
          serviceAccountName: infralib-agent@entigo-infralib.iam.gserviceaccount.com
          maxRetries: 0
