apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: entigo-infralib-apply
spec:
  template:
    spec:
      containers:
        - image: k8s.gcr.io/echoserver:1.10
          ports:
            - containerPort: 8080
