apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: entigo-infralib
deploy:
  cloudrun: {}
profiles:
  - name: plan
    manifests:
      rawYaml:
        - entigo-infralib-plan.yaml
  - name: apply
    manifests:
      rawYaml:
        - entigo-infralib-apply.yaml
