apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: plan-cloudrun-job
description: Terraform plan
run:
  location: projects/entigo-infralib/locations/europe-north1
executionConfigs:
  - usages:
      - RENDER
      - DEPLOY
    serviceAccount: infralib-agent@entigo-infralib.iam.gserviceaccount.com