name: PR test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'examples/**'
      - 'deploy_yaml/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/test.yaml
    with:
      pr-branch: ${{ github.event.pull_request.head.ref }}
    secrets: inherit
